## Numpy 

In [61]:
lists = ["hello",1,2,3,5,5]
lists

['hello', 1, 2, 3, 5, 5]

In [19]:
lists.append(10)

In [20]:
lists

['hello', 1, 2, 3, 5, 5, 10]

In [21]:
lists.insert(2,15)

In [22]:
lists

['hello', 1, 15, 2, 3, 5, 5, 10]

In [32]:
s = {1,1,2,2,3,4,5,6}
type(s)

set

In [26]:
s.remove(4)

In [28]:
s.add(9)

In [29]:
s

{1, 2, 3, 5, 6, 9}

In [35]:
s = set({1,2,3,5,3,3,4,6})
type(s)

set

In [36]:
import numpy as np
array = np.array([1,2,3,4,5,6,7])

In [37]:
array

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
print(np.max(array))

7


In [40]:
print(np.min(array))

1


In [43]:
print(np.sum(array))

28


In [55]:
print(type(array))

<class 'numpy.ndarray'>


In [56]:
l = [5,3,9,6,1,4,3,8,2,0]

In [60]:
l.sort()
print(l)

[0, 1, 2, 3, 3, 4, 5, 6, 8, 9]


In [59]:
l.sort(reverse = True)
print(l)

[9, 8, 6, 5, 4, 3, 3, 2, 1, 0]


In [74]:
import numpy as np

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)



Matrix a : 
 [[     4294967296   2353642078208]
 [           1044 140733193388800]]


In [77]:
np.zeros([2,2],dtype = int)

array([[0, 0],
       [0, 0]])

In [78]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [80]:
np.full([3,3],4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [81]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = a+b
print(add_ans)

add_ans = np.add(a, b)
print(add_ans)

c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [82]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = a-b
print(sub_ans)

[ 3 67  3 70]


In [83]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = a*b
print(mul_ans)

[  10  360  130 3000]


In [84]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = a/b
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [89]:
a = np.arange(10,0,-1) 
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [96]:
np.arange(1,51,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [97]:
import numpy as np

a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)

newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [100]:
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)


 A sequential array with a negative step: 
 [10  8  6  4  2]


In [99]:
print(np.array([3, 1, 2 ]))

[3 1 2]


In [101]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [102]:
ar = np.array([5,3,6])
print(np.reshape(ar,(3,1)))

[[5]
 [3]
 [6]]
